# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooly_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='class_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
