# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooly_app', '0002_auto_20170423_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=256),
        ),
    ]
